# Generated by Django 5.1.1 on 2024-10-03 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_cat_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='ratings',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('cat', 'user')},
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
        migrations.AlterField(
            model_name='rating',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cat.cat'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
